name: Alex Herrity
favicon: null
layout_spectrum: 0.49922
typography_spectrum: 0
title: Alex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffef'
    - '#342415'
    - '#d4cbba'
    - '#9b845a'
    - '#67573d'
  brandStrength: 0.6875
  lightness: 0.6709979325532913
  saturation: 0.795146296499297
  rhythmicContrast: 0.7389281808864325
purpose: []
